# --- MAPEAMENTO DOS CONTAINERS INTERNOS ---
upstream main_upstream {
    server c001-web-main:80;
}

upstream portal_upstream {
    server c002-web-portal:80;
}

upstream suporte_upstream {
    server c003-web-suporte:80;
}

# --- PÁGINA PADRÃO (LOCALHOST) ---
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

# --- PROXY PARA: nexustech.com.br ---
server {
    listen       80;
    listen  [::]:80;
    server_name  nexustech.com.br www.nexustech.com.br;

    access_log  /var/log/nginx/main.access.log  main;

    location / {
        proxy_pass http://main_upstream;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

# --- PROXY PARA: portal.nexustech.com.br ---
server {
    listen       80;
    listen  [::]:80;
    server_name  portal.nexustech.com.br;

    access_log  /var/log/nginx/portal.access.log  main;

    location / {
        proxy_pass http://portal_upstream;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

# --- PROXY PARA: suporte.nexustech.com.br ---
server {
    listen       80;
    listen  [::]:80;
    server_name  suporte.nexustech.com.br;

    access_log  /var/log/nginx/suporte.access.log  main;

    location / {
        proxy_pass http://suporte_upstream;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}