services:

  # --- PROXY REVERSO DEDICADO ---
  proxy-server:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: nexustech-proxy
    container_name: p001-proxy-server
    ports:
      - "80:80"  # Expondo apenas a porta 80 para acesso externo
    networks:
      - nexustech-network
    restart: always
    depends_on:
      - web-main
      - web-portal
      - web-support

  # --- SITE PRINCIPAL ---
  web-main:
    build:
      context: ./web/site-main
      dockerfile: Dockerfile
    image: nexustech-web-main
    container_name: c001-web-main
    networks:
      - nexustech-network
    restart: always

  # --- PORTAL ---
  web-portal:
    build:
      context: ./web/site-portal
      dockerfile: Dockerfile
    image: nexustech-web-portal
    container_name: c002-web-portal
    networks:
      - nexustech-network
    restart: always

  # --- SUPORTE ---
  web-support:
    build:
      context: ./web/site-support
      dockerfile: Dockerfile
    image: nexustech-web-support
    container_name: c003-web-support
    networks:
      - nexustech-network
    restart: always

  # --- SERVIÇO DE DNS (BIND9) ---
  dns-server:
    build: 
      context: ./dns
      dockerfile: Dockerfile
    image: nexustech-dns
    container_name: d001-dns-server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./dns/named.conf.local:/etc/bind/named.conf.local
      - ./dns/nexustech.com.br:/etc/bind/nexustech.com.br
    networks:
      - nexustech-network
    restart: always

  # --- SERVIÇO DE E-MAIL (POSTFIX + DOVECOT) ---
  mail-server:
    build:
      context: ./mail
      dockerfile: Dockerfile
    image: nexustech-mail
    container_name: m001-mail-server
    ports:
      - "25:25"   # SMTP
      - "143:143" # IMAP
      - "110:110" # POP3
    volumes:
      - ./mail_data:/var/mail/vmail
    networks:
      - nexustech-network
    restart: always

networks:
  nexustech-network:
    driver: bridge