# --- 1. SITE PRINCIPAL (NEXUSTECH.COM.BR) ---
server {
    listen 80;
    server_name nexustech.com.br www.nexustech.com.br;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}

# --- 2. PROXY REVERSO PARA O PORTAL ---
server {
    listen 80;
    server_name portal.nexustech.com.br;

    location / {
        # Joga o tráfego para o nome do container do portal na rede do Docker
        proxy_pass http://c002-web-portal:80;
        
        # Repassa os cabeçalhos originais para o container de trás saber quem está acessando
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

# --- 3. PROXY REVERSO PARA O SUPORTE ---
server {
    listen 80;
    server_name suporte.nexustech.com.br;

    location / {
        # Joga o tráfego para o nome do container de suporte na rede do Docker
        proxy_pass http://c003-web-support:80;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}