# --- SERVIÇO DE ACESSO IMAP (LEITURA DE E-MAILS) ---
service imap-login {
  inet_listener imap {
  }
  inet_listener imaps {
  }
}

# --- SERVIÇO DE ACESSO POP3 ---
service pop3-login {
  inet_listener pop3 {
  }
  inet_listener pop3s {
  }
}

# --- SERVIÇO DE SUBMISSÃO DE MENSAGENS ---
service submission-login {
  inet_listener submission {
  }
}

# --- PROTOCOLO DE ENTREGA LOCAL (LMTP) ---
service lmtp {
  unix_listener lmtp {
  }
}

service imap {
}

service pop3 {
}

service submission {
}

# --- SÓQUETES DE AUTENTICAÇÃO ---
service auth {
  unix_listener auth-userdb {
  }

  # ALTERAÇÃO DA ATIVIDADE: Integração essencial para autenticação do Postfix (Porta 25)
  unix_listener /var/spool/postfix/private/auth {
    mode = 0660
    user = postfix
    group = postfix
  }
}

service auth-worker {
}

service dict {
  unix_listener dict {
  }
}